version: '3.4'

services:

  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    depends_on: 
        - db

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Tuan123!@#
    ports: 
        - 1433:1433